import { mysqlTable, varchar, int, mysqlEnum } from 'drizzle-orm/mysql-core';
export const EjercicioSchema = mysqlTable('ejercicios', {
  id: int().autoincrement().primaryKey(),
  nombre: varchar({ length: 50 }).notNull(),
  descripcion: varchar({ length: 200 }).notNull(),
  repeticiones: varchar({ length: 10 }).notNull(),
  descanso: varchar({ length: 20 }).notNull(),
  ejecucion: varchar({ length: 255 }).notNull(),
  tempo: varchar({ length: 10 }).notNull(),
  grupoMuscular: mysqlEnum([
    'PECTORAL',
    'ESPALDA',
    'TRAPECIO',
    'DELTOIDES_ANTERIOR',
    'DELTOIDES_MEDIO',
    'DELTOIDES_POSTERIOR',
    'TRICEPS',
    'BICEPS',
    'ANTEBRAZO',
    'ABDOMEN',
    'GLUTEOS',
    'CUADRICEPS',
    'ISQUIOSURALES',
    'PANTORILLAS',
    'ADUCTORES',
    'CARDIOVASCULAR',
    'CALENTAMIENTO',
  ]).default('PECTORAL'),
});
