export const RECUPERACION_HISTORICA = [
  'PRESENTA DOLOR POR HASTA 3 DIAS DESPUES DEL ENTRENAMIENTO',
  'PRESENTA DOLOR POR HASTA 2 DIAS DESPUES DEL ENTRENAMIENTO',
  'PRESENTA DOLOR POR HASTA 1 DIA DESPUES DEL ENTRENAMIENTO',
  'RARAMENTE SE PRESENTA DOLOR POR MAS DE 1 DIA DESPUES DEL ENTRENAMIENTO',
  'RARAMENTE SE PRESENTA DOLOR POR MAS DE 1 DIA DESPUES DEL ENTRENAMIENTO Y RESPONDE A CARGAS DE TRABAJO ALTAS',
] as const;

export type RecuperacionHistoricaType = (typeof RECUPERACION_HISTORICA)[number];
