export const VOLUMEN_TRABAJO = [
  'FRECUENCIA DE 1 ACCESORIOS MINIMO',
  'FRECUENCIA DE 1-2 ACCESORIOS MODERADO',
  'FRECUENCIA DE 2 ACCESORIOS SIGNIFICATIVO',
  'FRECUENCIA DE 2-3 ACCESORIOS MODERADO A SIGNIFICATIVO',
  'FRECUENCIA DE 3 ACCESORIOS MODERADO A SIGNIFICATIVO',
] as const;

export type VolumenTrabajoType = (typeof VOLUMEN_TRABAJO)[number];
